INSERT INTO muscle (id, name) VALUES (1, 'Neck');
INSERT INTO muscle (id, name) VALUES (2, 'Front Deltoid');
INSERT INTO muscle (id, name) VALUES (3, 'Side Deltoid');
INSERT INTO muscle (id, name) VALUES (4, 'Triceps');
INSERT INTO muscle (id, name) VALUES (5, 'Tibialis');
INSERT INTO muscle (id, name) VALUES (6, 'Calves');
INSERT INTO muscle (id, name) VALUES (7, 'Chest');
INSERT INTO muscle (id, name) VALUES (8, 'Biceps');
INSERT INTO muscle (id, name) VALUES (9, 'Trapezius');
INSERT INTO muscle (id, name) VALUES (10, 'Forearms');
INSERT INTO muscle (id, name) VALUES (11, 'Abs');
INSERT INTO muscle (id, name) VALUES (12, 'Obliques');
INSERT INTO muscle (id, name) VALUES (13, 'Quads');
INSERT INTO muscle (id, name) VALUES (14, 'Adductors');
INSERT INTO muscle (id, name) VALUES (15, 'Abductors');
INSERT INTO muscle (id, name) VALUES (16, 'Knees');
INSERT INTO muscle (id, name) VALUES (17, 'Lats');
INSERT INTO muscle (id, name) VALUES (18, 'Upper Back');
INSERT INTO muscle (id, name) VALUES (19, 'Rear Deltoids');
INSERT INTO muscle (id, name) VALUES (20, 'Lower Back');
INSERT INTO muscle (id, name) VALUES (21, 'Glutes');
INSERT INTO muscle (id, name) VALUES (22, 'Hamstrings');